package com.example.worldlist3dapp;

import java.util.ArrayList;
import java.util.List;

public class CountryData {

    // Method to get the country names and image resource IDs
    public static List<CountryInfo> getCountriesInfo() {
        List<CountryInfo> countries = new ArrayList<>();

        // Add country names and corresponding image resource IDs
        countries.add(new CountryInfo("Afghanistan", R.drawable.afghanistan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Albania", R.drawable.albania, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Andorra", R.drawable.andorra, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Angola", R.drawable.angola, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Antigua and Barbuda", R.drawable.antiguaandbarbuda, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Argentina", R.drawable.argentina, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Armenia", R.drawable.armenia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Australia", R.drawable.australia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Austria", R.drawable.austria, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Azerbaijan", R.drawable.azerbaijan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Bahamas", R.drawable.bahamas, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Bahrain", R.drawable.bahrain, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Bangladesh", R.drawable.bangladesh, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Barbados", R.drawable.barbados, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Belarus", R.drawable.belarus, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Belgium", R.drawable.belgium, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Belize", R.drawable.belize, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Benin", R.drawable.benin, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Bhutan", R.drawable.bhutan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Bolivia", R.drawable.bolivia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Bosnia and Herzegovina", R.drawable.bosniaherzegovina, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Botswana", R.drawable.botswana, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Brazil", R.drawable.brazil, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Brunei", R.drawable.brunei, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Bulgaria", R.drawable.bulgaria, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Burkina Faso", R.drawable.burkinafaso, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Burundi", R.drawable.burundi, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Cabo Verde", R.drawable.caboverde, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Cambodia", R.drawable.cambodia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Cameroon", R.drawable.cameroon, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Canada", R.drawable.canada, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Central African Republic", R.drawable.centralafricanrepublic, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Chad", R.drawable.chad, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Chile", R.drawable.chile, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("China", R.drawable.china, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Colombia", R.drawable.colombia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Comoros", R.drawable.comoros, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Congo", R.drawable.congo, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Costa Rica", R.drawable.costarica, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Croatia", R.drawable.croatia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Cuba", R.drawable.cuba, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Cyprus", R.drawable.cyprus, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("DRC Congo", R.drawable.democraticrepubliccongo, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Denmark", R.drawable.denmark, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Djibouti", R.drawable.djibouti, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Dominica", R.drawable.dominica, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Dominican Republic", R.drawable.dominicanrepublic, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("East Timor", R.drawable.easttimor, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Ecuador", R.drawable.ecuador, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Egypt", R.drawable.egypt, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("El Salvador", R.drawable.elsalvador, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Equatorial Guinea", R.drawable.equatorialguinea, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Eritrea", R.drawable.eritrea, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Estonia", R.drawable.estonia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Eswatini", R.drawable.eswatini, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Ethiopia", R.drawable.ethiopia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Fiji", R.drawable.fiji, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Finland", R.drawable.finland, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("France", R.drawable.france, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Gabon", R.drawable.gabon, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Georgia", R.drawable.georgia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Germany", R.drawable.germany, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Ghana", R.drawable.ghana, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Greece", R.drawable.greece, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Grenada", R.drawable.grenada, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Guatemala", R.drawable.guatemala, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Guinea", R.drawable.guinea, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Guinea Bissau", R.drawable.guineabissau, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Guyana", R.drawable.guyana, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Haiti", R.drawable.haiti, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Honduras", R.drawable.honduras, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Hungary", R.drawable.hungary, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Iceland", R.drawable.iceland, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("India", R.drawable.india, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Indonesia", R.drawable.indonesia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Iran", R.drawable.iran, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Iraq", R.drawable.iraq, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Ireland", R.drawable.ireland, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Israel", R.drawable.israel, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Italy", R.drawable.italy, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Ivory Coast", R.drawable.ivorycoast, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Jamaica", R.drawable.jamaica, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Japan", R.drawable.japan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Jordan", R.drawable.jordan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Kazakhstan", R.drawable.kazakhstan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Kenya", R.drawable.kenya, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Kiribati", R.drawable.kiribati, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Kosovo", R.drawable.kosovo, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Kuwait", R.drawable.kuwait, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Kyrgyzstan", R.drawable.kyrgyzstan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Laos", R.drawable.laos, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Latvia", R.drawable.latvia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Lebanon", R.drawable.lebanon, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Lesotho", R.drawable.lesotho, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Liberia", R.drawable.liberia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Libya", R.drawable.libya, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Liechtenstein", R.drawable.liechtenstein, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Lithuania", R.drawable.lithuania, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Luxembourg", R.drawable.luxembourg, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Madagascar", R.drawable.madagascar, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Malawi", R.drawable.malawi, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Malaysia", R.drawable.malaysia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Maldives", R.drawable.maldives, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Mali", R.drawable.mali, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Malta", R.drawable.malta, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Marshall Islands", R.drawable.marshallislands, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Mauritania", R.drawable.mauritania, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Mauritius", R.drawable.mauritius, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Mexico", R.drawable.mexico, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Micronesia", R.drawable.micronesia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Moldova", R.drawable.moldova, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Monaco", R.drawable.monaco, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Mongolia", R.drawable.mongolia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Montenegro", R.drawable.montenegro, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Morocco", R.drawable.morocco, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Mozambique", R.drawable.mozambique, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Myanmar", R.drawable.myanmar, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Namibia", R.drawable.namibia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Nauru", R.drawable.nauru, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Nepal", R.drawable.nepal, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Netherlands", R.drawable.netherlands, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("New Zealand", R.drawable.newzealand,"Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Nicaragua", R.drawable.nicaragua, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Niger", R.drawable.niger, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Nigeria", R.drawable.nigeria, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("North Korea", R.drawable.northkorea, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("North Macedonia", R.drawable.northmacedonia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Norway", R.drawable.norway, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Oman", R.drawable.oman, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Pakistan", R.drawable.pakistan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Palau", R.drawable.palau, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Panama", R.drawable.panama, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Papua New Guinea", R.drawable.papuanewguinea, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Paraguay", R.drawable.paraguay, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Peru", R.drawable.peru, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Philippines", R.drawable.philippines, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Poland", R.drawable.poland, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Portugal", R.drawable.portugal, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Qatar", R.drawable.qatar, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Romania", R.drawable.romania, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Russia", R.drawable.russia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Rwanda", R.drawable.rwanda, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Saint Kitts and Nevis", R.drawable.saintkittsandnevis, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Saint Lucia", R.drawable.saintlucia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Saint Vincent and the Grenadines", R.drawable.saintvincentandthegrenadines, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Samoa", R.drawable.samoa, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("San Marino", R.drawable.sanmarino, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("São Tomé and Principe", R.drawable.saotomeandprincipe, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Saudi Arabia", R.drawable.saudiarabia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Senegal", R.drawable.senegal, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Serbia", R.drawable.serbia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Seychelles", R.drawable.seychelles, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Sierra Leone", R.drawable.sierraleone, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Singapore", R.drawable.singapore, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Slovakia", R.drawable.slovakia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Slovenia", R.drawable.slovenia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Solomon Islands", R.drawable.solomonislands, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Somalia", R.drawable.somalia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("South Africa", R.drawable.southafrica, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("South Korea", R.drawable.southkorea, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("South Sudan", R.drawable.southsudan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Spain", R.drawable.spain, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Sri Lanka", R.drawable.srilanka, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Sudan", R.drawable.sudan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Suriname", R.drawable.suriname, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Sweden", R.drawable.sweden, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Switzerland", R.drawable.switzerland, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Syria", R.drawable.syria, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Taiwan", R.drawable.taiwan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Tajikistan", R.drawable.tajikistan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Tanzania", R.drawable.tanzania, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Thailand", R.drawable.thailand, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("The Gambia", R.drawable.thegambia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Togo", R.drawable.togo, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Tonga", R.drawable.tonga, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Trinidad and Tobago", R.drawable.trinidadandtobago, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Tunisia", R.drawable.tunisia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Turkey", R.drawable.turkey, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Turkmenistan", R.drawable.turkmenistan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Tuvalu", R.drawable.tuvalu, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Uganda", R.drawable.uganda, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Ukraine", R.drawable.ukraine, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("United Arab Emirates", R.drawable.unitedarabemirates, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("United Kingdom", R.drawable.unitedkingdom, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("United States", R.drawable.unitedstates, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Uruguay", R.drawable.uruguay, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Uzbekistan", R.drawable.uzbekistan, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Vanuatu", R.drawable.vanuatu, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Vatican City", R.drawable.vaticancity, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Venezuela", R.drawable.venezuela, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Vietnam", R.drawable.vietnam, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Yemen", R.drawable.yemen, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Zambia", R.drawable.zambia, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));
        countries.add(new CountryInfo("Zimbabwe", R.drawable.zimbabwe, "Explore Afghanistan’s rich history, ancient cities like Herat and Kabul, and the beautiful Hindu Kush mountains."));

        return countries;
    }
}